[package]
name = "ncm-el-extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "api"

[dependencies]
ncmapi = "0.1.8"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
